# Example of a scheduled job that commits new data file

name: test

# Schedule a job
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 1 * * *'
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: install packages
        run: |
          sudo apt-get -q update
          sudo apt-get install python3-bs4
          sudo apt-get install python3-requests
          sudo apt-get install xmltv-util

      - name: run
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" ?>' > test.xml
          echo '<tv generator-info-name="sdg" generator-info-url="http://www.satdreamgr.com">' >> test.xml
          python test.py >> test.xml
          echo '</tv>' >> test.xml
          tv_sort --by-channel --duplicate-error --output new.xml test.xml
          mv new.xml test.xml
          gzip -k test.xml

      - name: commit 
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add test.xml
          git commit -m "new data from job ${{ github.run_number }}"
          git pull origin "${{ github.ref }}" --autostash --rebase -Xours
          git push origin "${{ github.ref }}"
          git log --name-only
          git status

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test
          release_name: test
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./test.xml.gz
          asset_name: test.xml.gz
          asset_content_type: application/gzip
